[tox]
envlist = py3{10-14}-{PySide6,cli},py314t-cli

[tool:pytest]
addopts = --verbose --faulthandler-timeout=10

[testenv]
labels =
    test
dependency_groups = test
download=true
commands =  {env_bin_dir}{/}pytest --basetemp={envtmpdir} {env:pytest_args:} {posargs}

[testenv:py3{10-}-PySide6]
labels =
    test
passenv =
    XAUTHORITY
    DISPLAY
    LocalAppData
set_env =
    QT_QPA_PLATFORM=offscreen

extras = gui
commands =  {env_bin_dir}{/}pytest --basetemp={envtmpdir} {env:pytest_args:} {posargs}

[testenv:mypy]
labels =
    lint
    correctness
dependency_groups = type-checking
setenv = MYPY_CACHE_DIR = {temp_dir}/.mypy_cache
commands = mypy {posargs: -p speedwagon_contrib}

[testenv:ruff]
labels =
    lint
    style
    correctness
skip_install = true
dependency_groups = static-analysis
commands =
    ruff check {posargs: {toxinidir}/speedwagon_contrib}
